

version: "3.9"

networks:
  vap-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: vap-mysql
    environment:
      MYSQL_DATABASE: vapdb
      MYSQL_USER: vap
      MYSQL_PASSWORD: vap123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - vap-network

  redis:
    image: redis:7
    container_name: vap-redis
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - vap-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: vap-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - vap-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: vap-kafka
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - vap-network

  backend:
    image: ${DOCKER_USERNAME}/vap-backend:latest
    container_name: vap-backend
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - vap-network

volumes:
  mysql_data:
